
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("0.6.18.3")]
 [assembly: AssemblyFileVersion("0.6.18.3")]
 [assembly: KSPAssembly("StateFunding", 0, 6, 18)]
